{"name": "test_user_can_log_in[2]", "status": "broken", "statusDetails": {"message": "KeyError: '2'", "trace": "E   KeyError: '2'"}, "parameters": [{"name": "id", "value": "'2'"}], "start": 1644365156052, "stop": 1644365156053, "uuid": "ea3155f5-7c18-431f-a151-de9f295a6eb1", "historyId": "0048dd233ffe9d43ca97e5a29c763024", "testCaseId": "3c0c80c1e8f7586509bf22a553a53fa9", "fullName": "test_login_page#test_user_can_log_in", "labels": [{"name": "tag", "value": "all_test"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "DESKTOP-UK0K253"}, {"name": "thread", "value": "1268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_page"}]}